apiVersion: v1
kind: Secret
metadata:
  name: repo-base
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: "infra"
  url: https://github.com/dss2194/k8s-local.git
type: Opaque
