---
name: Mirror Repository

on:
  push:
    branches:
      - main
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This must be set to 0 to avoid shallow cloning.

      - name: Mirror Repository
        uses: 0xTheProDev/gitlab-mirror@v1
        with:
          password: ${{ secrets.GITLAB_PAT }}
          project-id: "software/k8s-local"
          username: "infra_dss"